version: '3.8'
services:
  db:
    build: ./DB
    container_name: postgres_db
    environment:
      POSTGRES_USER: unifaat
      POSTGRES_PASSWORD: unifaat
      POSTGRES_DB: Escola
    ports:
      - "2000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: